# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: RUN CONDO TESTS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      test-chunks: ${{ steps['set-test-chunks'].outputs['test-chunks'] }}
      test-chunk-ids: ${{ steps['set-test-chunk-ids'].outputs['test-chunk-ids'] }}
    strategy:
      matrix:
        node-version: [ 14.x ]
        database: [ "postgresql://postgres:postgres@127.0.0.1/main" ]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Docker compose up databases
        run: |
          cp .env.example .env
          docker-compose up -d postgresdb redis

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Install kmigrator dependencies
        run: |
          pip3 install django
          pip3 install psycopg2-binary

      - name: test front build
        run: |
          set -x
          echo '# Build time .env config!' > .env
          echo 'COOKIE_SECRET=undefined' >> .env
          echo 'DATABASE_URL=undefined' >> .env
          echo 'WORKER_REDIS_URL=undefined' >> .env
          echo 'NODE_ENV=production' >> .env
          yarn workspace @app/condo build

      - name: Set test chunks name
        id: set-test-chunks
        run: |
          cd ./apps/condo/
          echo "::set-output name=test-chunks::$(yarn --silent jest --listTests --json | jq -cM '[_nwise(length / 2 | floor)]')"

      - name: Set chunk ids
        id: set-test-chunk-ids
        run: echo "::set-output name=test-chunk-ids::$(echo $CHUNKS | jq -cM 'to_entries | map(.key)')"
        env:
          CHUNKS: ${{ steps['set-test-chunks'].outputs['test-chunks'] }}

  test:
    runs-on: ubuntu-latest
    name: test (chunk №${{ matrix.chunk }})
    needs:
      - setup

    strategy:
      matrix:
        chunk: ${{ fromJson(needs.setup.outputs['test-chunk-ids']) }}
        node-version: [ 14.x ]
        database: [ "postgresql://postgres:postgres@127.0.0.1/main" ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Docker compose up databases
        run: |
          cp .env.example .env
          docker-compose up -d postgresdb redis

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          pip3 install django
          pip3 install psycopg2-binary

      - name: run tests for ${{ matrix.chunk }}
        run: |
          set -x
          cp .env.example .env
          export NODE_ENV=test
          export NOTIFICATION__SEND_ALL_MESSAGES_TO_CONSOLE=true
          export NOTIFICATION__DISABLE_LOGGING=true
          export WORKER_CONCURRENCY=50

          [[ $DATABASE_URL == postgresql* ]] && yarn workspace @app/condo migrate

          yarn workspace @app/condo dev &
          bash ./.github/workflows/waitForLocalhostApiReady.sh

          # check migrations
          yarn workspace @app/condo makemigrations --check &> /dev/null

          yarn workspace @app/condo worker &
          sleep 3

          # And check background processes!
          [[ $(jobs | wc -l | tr -d ' ') != '2' ]] && exit 2
          sleep 3

          echo $CHUNKS | jq '.[${{ matrix.chunk }}] | .[] | @text' | xargs yarn workspace @app/condo test --silent --testTimeout=15000 --forceExit --coverage --maxWorkers=2

          # Note: we need to stop background worker! because packages tests use the same redis queue
          kill $(jobs -p) || echo 'background worker and dev server is already killed!'
          killall node || echo 'no node processes'

        env:
          DATABASE_URL: ${{ matrix.database }}
          NODE_ENV: development
          DISABLE_LOGGING: true
          CHUNKS: ${{ needs.setup.outputs['test-chunks'] }}

  core-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
        database: [ "postgresql://postgres:postgres@127.0.0.1/main" ]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Docker compose up databases
        run: |
          cp .env.example .env
          docker-compose up -d postgresdb redis

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          pip3 install django
          pip3 install psycopg2-binary

      - name: Run core tests
        run: |
          set -x
          cp .env.example .env
          export NODE_ENV=test
          export NOTIFICATION__SEND_ALL_MESSAGES_TO_CONSOLE=true
          export NOTIFICATION__DISABLE_LOGGING=true
          export WORKER_CONCURRENCY=50

          [[ $DATABASE_URL == postgresql* ]] && yarn workspace @app/condo migrate

          yarn workspace @app/condo dev &
          bash ./.github/workflows/waitForLocalhostApiReady.sh

          yarn workspace @app/condo makemigrations --check &> /dev/null

          yarn workspace @app/condo worker &
          sleep 3

          [[ $(jobs | wc -l | tr -d ' ') != '2' ]] && exit 2
          sleep 3

          yarn jest ./packages/@core.keystone --maxWorkers=2

          yarn workspace @app/condo lint-schema
        env:
          DATABASE_URL: ${{ matrix.database }}
          NODE_ENV: development
          DISABLE_LOGGING: true
